# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c7f09659ed08510f0c5f65e547ca7626eed9d19a08a1fcd683aa416789970e29119e2f9adc88476af1491a44b8d1041bb0ec2ad902bd62b799a7a6c3eda1a42

test:
  secret_key_base: 82abdfca41b5c99e511d670cbf64a90d15dfa2b71ae2124ac82bcb253066fbddcd0f5ddc25d3e84cb394faf80ce4888786df1b8849e2f7d8c883e02346419df5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
